# Generated by Django 3.1.2 on 2020-11-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consols',
            fields=[
                ('create_date', models.DateField(auto_now_add=True)),
                ('mawb', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=50)),
                ('cutoff', models.DateField()),
                ('destination', models.CharField(max_length=4)),
                ('shipment_status', models.BooleanField(default=True)),
            ],
        ),
    ]
