# Generated by Django 3.1.2 on 2020-11-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consols', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consols',
            options={'verbose_name': 'Consol'},
        ),
    ]
