# Generated by Django 3.1.2 on 2020-11-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_images', models.ImageField(blank=True, null=True, upload_to='shipments/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingUnits',
            fields=[
                ('locations', models.CharField(choices=[('JFK', 'JFK'), ('LAX', 'LAX'), ('ORD', 'ORD')], default='JFK', max_length=3)),
                ('on_hand', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('shipper', models.CharField(max_length=50)),
                ('consignee', models.CharField(max_length=50)),
                ('width', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('gross_weight', models.PositiveIntegerField()),
                ('unit_count', models.PositiveIntegerField()),
                ('pallet_count', models.PositiveIntegerField()),
                ('heat_treated_pallet_count', models.PositiveIntegerField()),
                ('remark', models.TextField()),
                ('shipment_status', models.BooleanField(default=False)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('hawb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hawbs', to='consols.consols')),
                ('mawb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mawbs', to='consols.consols')),
            ],
            options={
                'ordering': ('on_hand',),
                'permissions': (('can_add_shipment', 'Can add a shipping unit'), ('can_modify', 'Can modify a shipment'), ('can_release', 'Can release a shipment'), ('can_delete', 'Can erase a shipment from existence')),
            },
        ),
    ]
