# Generated by Django 3.1.2 on 2020-11-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_auto_20201101_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentimages',
            options={'verbose_name': 'Shipment Image'},
        ),
        migrations.AlterModelOptions(
            name='shippingunits',
            options={'ordering': ('on_hand',), 'permissions': (('can_add_shipment', 'Can add a shipping unit'), ('can_modify', 'Can modify a shipment'), ('can_release', 'Can release a shipment'), ('can_delete', 'Can erase a shipment from existence')), 'verbose_name': 'Shipping Unit'},
        ),
    ]
