# Generated by Django 3.1.2 on 2020-12-26 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_auto_20201103_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consols',
            fields=[
                ('create_date', models.DateField(auto_now_add=True)),
                ('mawb', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=50)),
                ('cutoff', models.DateField()),
                ('destination', models.CharField(max_length=4)),
                ('shipment_status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Consol',
            },
        ),
        migrations.AlterField(
            model_name='shippingunits',
            name='hawb',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='shippingunits',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingunits',
            name='mawb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mawbs', to='shipments.consols'),
        ),
    ]
