# Generated by Django 3.1.2 on 2020-12-28 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20201226_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consols',
            name='client',
        ),
    ]
