# Generated by Django 3.1.2 on 2021-01-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_remove_consols_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consols',
            name='shipment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shippingunits',
            name='shipment_status',
            field=models.CharField(choices=[('not_ready', 'Not Ready'), ('ready', 'Ready'), ('completed', 'Completed'), ('issue', 'Issue')], default='not_ready', max_length=15),
        ),
    ]
